---
FILE_NAMES:
  - !!str C:/Users/doomu/OneDrive/Рабочий стол/Test_2/roi_align_/roi_align__specdata.hdf5
  - !!str C:/Users/doomu/OneDrive/Рабочий стол/Test_2/roi_align_10_5/roi_align_10_5_specdata.hdf5
FOLDERS: !!str HDF\\Data\\
CASH: !!str Cash\\cash.hdf5
DATASET: !!str roi1_e046/00/peaklists
REF: !!float 193.07712
DEV: !!float 1
BW: !!float 0.02
NDOTS: !!int 100000
...