---
FILE_NAMES:
  - !!str E031_032_033_5mg_60C_90sec_9AA_161023_rawdata.hdf5
  - !!str E031_032_033_5mg_60C_90sec_9AA_161023.hdf5
FOLDERS: !!str HDF\\Data\\
CASH: !!str Cash\\cash.hdf5
DATASET: !!str roi2_e033/00/features
REF: !!float 193.07712
DEV: !!float 0.2
...